apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
  namespace: dev
  labels:
    app: express-backend
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
        environment: development
    spec:
      containers:
      - name: express-backend
        image: docker.io/pranesh25joshi/automated-pipeline:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10