apiVersion: v1
kind: Service
metadata:
  name: express-backend
  namespace: dev
  labels:
    app: express-backend
    environment: development
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: express-backend