apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
  namespace: prod
  labels:
    app: express-backend
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
        environment: production
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: express-backend
        image: docker.io/pranesh25joshi/automated-pipeline:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10