apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
  namespace: staging
  labels:
    app: express-backend
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
        environment: staging
    spec:
      containers:
      - name: express-backend
        image: ghcr.io/pranesh25joshi/automated-pipeline:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "staging"
        - name: PORT
          value: "3000"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.3"
            memory: "384Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10