apiVersion: v1
kind: Service
metadata:
  name: express-backend
  namespace: staging
  labels:
    app: express-backend
    environment: staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: express-backend